name       : python-numpydoc
version    : 1.4.0
release    : 12
source     :
    - https://github.com/numpy/numpydoc/archive/refs/tags/v1.4.0.tar.gz : a4642fba5b689d08c79350e05861a53daf70a6b45da5870294893514809735d8
homepage   : https://github.com/numpy/numpydoc
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
component  : programming.python
summary    : Numpy's Sphinx extensions
description: |
    Numpy's documentation uses several custom extensions to Sphinx. These are shipped in this numpydoc package, in case you want to make use of them in third-party projects.
networking : yes # Needed for tests
builddeps  :
    - python-jinja      # check
    - python-pytest-cov # check
    - python-sphinx     # check
rundeps    :
    - python-jinja
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
