name       : python-numpydoc
version    : 1.2.0
release    : 8
source     :
    - https://github.com/numpy/numpydoc/archive/v1.2.0.tar.gz : 48da9a15c1f14517861b848188f8c8ab88482b0685bd4a140031aec187c35158
homepage   : https://github.com/numpy/numpydoc
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
component  : programming.python
summary    : Numpy's Sphinx extensions
description: |
    Numpy's documentation uses several custom extensions to Sphinx. These are shipped in this numpydoc package, in case you want to make use of them in third-party projects.
networking : yes # Needed for tests
builddeps  :
    - pkgconfig(python3)
    - matplotlib
    - python-jinja
    - python-pytest-cov
    - python-sphinx
rundeps    :
    - python-jinja
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
