name       : python-numpydoc
version    : 0.9.1
release    : 4
source     :
    - https://github.com/numpy/numpydoc/archive/v0.9.1.tar.gz : b480ef5a7ed680a2ecb1615c44a5becb8eacb2be94b58b200340f0a2a458b854
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - Python-2.0
component  : programming.python
summary    : Numpy's Sphinx extensions
description: |
    Numpy's documentation uses several custom extensions to Sphinx. These are shipped in this numpydoc package, in case you want to make use of them in third-party projects.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-jinja
    - python-sphinx
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
